### ISSUE TITLE
Inheriting from jetty image – war is not deployed correctly

### ISSUE THREAD

**Issue by doronl** [docker-library/docs#344]
Hi,

  I have the below Dockerfile, when i run the built image I am not able to connect to the web site, am I doing somthing wrong? are there any other methods to deploy war rather than inheriting? 

Thanks

FROM jetty:9.3-jre8

ADD ./demoweb.war "$JETTY_BASE/webapps/demoweb.war"

**Comment by md5** [comment]
Could you provide the output of `docker logs $CONTAINER`? I just tried this with the Tomcat sample application from [here](https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/) and it worked fine.

The output of `docker images jetty:9.3-jre8` may also be helpful, as well as your `docker version` output.

**Comment by md5** [comment]
Also, I'm not sure what you mean by "inheriting", but the other way to deploy a WAR file is to mount it into the container with `-v "$(pwd)/demoweb.war:/var/lib/jetty/webapps/demoweb.war"`.

**Comment by doronl** [comment]
Thanks Mike for the response, I will have the environment beginning of next
week and get back to you via github with the inputs.



Regards,

  Doron

**Comment by doronl** [comment]
Here are the commands outputs:

docker version output:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64

docker logs $CONTAINER output:

2015-09-20 10:09:47.919:INFO::main: Logging initialized @317ms
2015-09-20 10:09:48.112:INFO:oejs.SetUIDListener:main: Setting umask=02
2015-09-20 10:09:48.138:INFO:oejs.SetUIDListener:main: Opened ServerConnector@7cf10a6f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2015-09-20 10:09:48.138:INFO:oejs.SetUIDListener:main: Setting GID=999
2015-09-20 10:09:48.139:INFO:oejs.SetUIDListener:main: Setting UID=999
2015-09-20 10:09:48.145:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2015-09-20 10:09:48.170:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
2015-09-20 10:09:48.244:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6276ae34{/demoweb,null,null}{/demoweb.war}
java.io.FileNotFoundException: /var/lib/jetty/webapps/demoweb.war (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:160)
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:470)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:474)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:510)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
2015-09-20 10:09:48.254:INFO:oejs.ServerConnector:main: Started ServerConnector@7cf10a6f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2015-09-20 10:09:48.255:INFO:oejs.Server:main: Started @654ms

**Comment by md5** [comment]
> /var/lib/jetty/webapps/demoweb.war (Permission denied)

That's your problem. The `jetty` user isn't able to read your WAR file. Can you check the permissions on `demoweb.war` inside and outside the container?

You probably need to run a command like `chmod a+r demoweb.war` outside the container.

**Comment by doronl** [comment]
I add in the DockerFile the following line and it works,
RUN chmod a+r "$JETTY_BASE/webapps/demoweb.war"

Thanks!

**Comment by md5** [comment]
@doronl Cool. You might want to consider changing the permissions on the WAR file in the source directory instead of running an extra command in the `Dockerfile`, but either should work.

Do you mind closing this issue if you consider it resolved? Thanks.

**Comment by doronl** [comment]
OK, this made the same effect, I removed it, Thanks!, you can close this one, 2 questions if I may:

1.	When deploying the same war directly on the same machine (not inside a container) this change was not required… is this due the fact that I run the local jetty with my account?, when I run a container (I use sudo docker run…) under which privileges the container runs (don’t have to answer, If you can refer me to the proper docs)? 
2.	A command like RUN chmod a+r "$JETTY_BASE/webapps/demoweb.war", is it creating another layer for the container file system?

Thanks

**Comment by md5** [comment]
1. Yes, that's due to the fact that you're running as your own account in that case and the file is owner-readable. The Jetty server runs as user `jetty` with UID 999 and GID 999, which is documented here: https://github.com/docker-library/docs/tree/master/jetty#security
2. Yes, it does create another layer.

If you don't mind closing the issue yourself, that would be great. I'm not a maintainer on this repo, just for the `jetty` image itself.

**Comment by yosifkit** [comment]
@md5, I got it :wink:.

**Comment by md5** [comment]
@yosifkit :+1:

**Comment by md5** [comment]
@navinSing Please open a new issue in the [`appropriate/docker-jetty`](https://github.com/appropriate/docker-jetty) repo.
