### ISSUE TITLE
elasticsearch crashes if config/scripts directory does not exist

### ISSUE THREAD

**Issue by sanori** [docker-library/docs#378]
If someone add a volume to `/usr/share/elasticsearch/config/` without `scripts` directory, elasticsearch fails to start with the following error.

```
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:218)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:195)
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:162)
        at org.elasticsearch.bootstrap.Security.configure(Security.java:100)
        at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:181)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

Is this intended action?

**Comment by yosifkit** [comment]
I believe so, the folders are created in the [image](https://github.com/docker-library/elasticsearch/blob/master/Dockerfile.template#L32-L35), but if there is a bind mount over it, you'll need to make sure the structure exists.  You'll also be hiding the `logging.yml` that makes sure the logs go to stdout.  If there is only one config file, it might be easier to just bind mount the single file, rather than the whole folder: `-v /my/local/config/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml`.

**Comment by sanori** [comment]
Understood. Thank you.
Then, it would be better to revise the information on https://hub.docker.com/_/elasticsearch/ that shows the following example
```
$ docker run -d -v "$PWD/config":/usr/share/elasticsearch/config elasticsearch
```
Is the source of that page https://github.com/docker-library/docs/blob/master/elasticsearch/README.md ?

**Comment by yosifkit** [comment]
A user can set `path.scripts` in their `elasticsearch.yml`, but yes, it would make it easier to mention mounting the file directly or that they will need a `scripts` directory in there.  That is the source of the description on the hub but you would need to edit `content.md` in that directory since readme is generated.

**Comment by Kitanotori** [comment]
How do I fix this problem on OSX? How do I run Elasticsearch container so that the config directory gets mounted?

**Comment by tianon** [comment]
Another option would be to let Docker itself create a volume on top of your `config` directory for scripts, ie: `docker run -v /some/path/config:/usr/share/elasticsearch/config -v /usr/share/elasticsearch/config/scripts elasticsearch:...`, which will force it to copy the contents of the image upwards into the container's volume

**Comment by mostolog** [comment]
Hmmm...seems **chmod o+r /some/path/config** before binding volume (_-v /some/path/config:/..._) worked for me.
