### ISSUE TITLE
docker run -d --name sentry-celery1 -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry celery worker not work

### ISSUE THREAD

**Issue by zhangjianpinghik** [docker-library/docs#605]
!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!
!! `sentry celery beat` is deprecated. !!
!!    Use `sentry run cron` instead.   !!
!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 152, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 87, in inner
    ctx.forward(django)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 552, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 26, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/django.py", line 23, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/sentry/management/commands/celery.py", line 35, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/beat.py", line 79, in run
    return beat().run()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/beat.py", line 83, in run
    self.start_scheduler()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/beat.py", line 95, in start_scheduler
    platforms.create_pidlock(self.pidfile)
  File "/usr/local/lib/python2.7/site-packages/celery/platforms.py", line 254, in create_pidlock
    pidlock = _create_pidlock(pidfile)
  File "/usr/local/lib/python2.7/site-packages/celery/platforms.py", line 264, in _create_pidlock
    pidlock.acquire()
  File "/usr/local/lib/python2.7/site-packages/celery/platforms.py", line 152, in acquire
    reraise(LockFailed, LockFailed(str(exc)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/celery/platforms.py", line 150, in acquire
    self.write_pid()
  File "/usr/local/lib/python2.7/site-packages/celery/platforms.py", line 211, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
**celery.platforms.LockFailed: [Errno 13] Permission denied: '/celerybeat.pid'**
celery beat v3.1.18 (Cipater) is starting.

**Comment by aleksanyan** [comment]
+1

**Comment by yosifkit** [comment]
Since this is about a specific image and not about the docs, this should really be reported over in https://github.com/getsentry/docker-sentry.  Many maintainers do not see issues reported here.
