### ISSUE TITLE
Sentry docs outdated? 

### ISSUE THREAD

**Issue by jean** [docker-library/docs#967]
1. The initial `upgrade` doesn't prompt to create a user (I created one using `createuser`).
2. web access fails:

```
14:15:21 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest
path:/auth/login/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'sentrysid': 'gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1da0cL:oheX1okO8EtfQMhngEkclzPpRp8'},
META:{u'CSRF_COOKIE': u'mW7mLInhWIsqZbQhaYlIQhZAeOeUr8dF',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'identity',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_COOKIE': 'sentrysid="gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1da0cL:oheX1okO8EtfQMhngEkclzPpRp8"',
 'HTTP_HOST': 'localhost:9000',
 'HTTP_USER_AGENT': 'Wget/1.17.1 (linux-gnu)',
 'PATH_INFO': u'/auth/login/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '172.17.0.1',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/auth/login/',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'f2ac594e246c',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.core': 3,
 'uwsgi.node': 'f2ac594e246c',
 'uwsgi.version': '2.0.15',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f77265a7780>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f77241d7360>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/error_500.py", line 22, in get_embed_config
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:15:21 [ERROR] root: Unable to fetch ProjectKey for internal project
14:15:21 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 67, in _get_public_dsn
    )[0]
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:15:21 [ERROR] root: Unable to fetch ProjectKey for internal project
14:15:21 [ERROR] sentry.errors: Internal project (id=1) does not exist
172.17.0.1 - - [25/Jul/2017:14:15:21 +0000] "GET /auth/login/ HTTP/1.1" 500 8631 "-" "Wget/1.17.1 (linux-gnu)"
```

This was after following https://github.com/docker-library/docs/tree/master/sentry step by step.

**Comment by tianon** [comment]
Sorry for the delay -- the maintainers of the Sentry official image do not actively monitor this repository, so this issue is likely to get more attention if you file it over on https://github.com/getsentry/docker-sentry/issues instead.  Thanks!
